### ISSUE TITLE
java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

### ISSUE THREAD

**Issue by ColaAndroid** [garretyoder/app-theme-engine#10]
I'm getting this fucking error when trying to open my app!!!

**Comment by garretyoder** [comment]
afollestad, app-theme-engine's developer took the repo down for the project when he discontinued it. Many apps still depend on it, so I kept my fork up as a mirror. However, I recommend using my own Colorful library as a better alternative that is not out of support. https://github.com/garretyoder/Colorful
