### ISSUE TITLE
Transparent toolbar

### ISSUE THREAD

**Issue by hefuyicoder** [garretyoder/app-theme-engine#2]
how to make transparent toolbar? I have try to return Color.TRANSPARENT in ATEToolbarCustomizer interface，it make effect in 19 ,and 23 and 24 is not success,the toolbar become white but not transparent.

**Comment by garretyoder** [comment]
If you wanted to make a toolbar transparent, the easiest way would be to use the ignore tag, and just set the toolbar's background color to transparent in xml.

**Comment by rakshith** [comment]
ate_ignore not working for the toolbar view, how to set the this value please explain

**Comment by garretyoder** [comment]
afollestad, app-theme-engine's developer took the repo down for the project when he discontinued it. Many apps still depend on it, so I kept my fork up as a mirror. However, I recommend using my own Colorful library as a better alternative that is not out of support. https://github.com/garretyoder/Colorful
