### ISSUE TITLE
Not supporting appcompat v-25

### ISSUE THREAD

**Issue by adasaddy** [garretyoder/app-theme-engine#3]
was working fine with appcompat v-23 but after updating compile sdk version to 25 app is crashing.

**Comment by garretyoder** [comment]
ATE has been dropped by the author long ago. I've kept it functional and updated as long as possible, but too much was changed in sdk25 for it to be worth it. I've deprecated it in favor of my new theme library https://github.com/garretyoder/Colorful

**Comment by Berlon** [comment]
That's odd....I am using this in sdk version 25 no issues. Except for that annoying lag when leaving settings.
