### ISSUE TITLE
Back icon(actionModeCloseDrawable) not shown in action mode

### ISSUE THREAD

**Issue by gulshan9958** [garretyoder/app-theme-engine#5]
Hi, this library is awsome, but issue i have found, when start Action mode, Back arrow not showing, pls see in screen shot.
Below code i am using to show action mode

`

      final Toolbar toolbar = (Toolbar) findViewById(R.id.appbar_toolbar);

        setSupportActionBar(toolbar);

        toolbar.setTitle(R.string.app_name);

        Button button = (Button) findViewById(R.id.button);

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //Starting action mode but not showing back icon
                ActionMode actionMode = toolbar.startActionMode(callback);
            }
        });

        ActionMode.Callback callback = new ActionMode.Callback() {

            @Override
            public boolean onPrepareActionMode(ActionMode mode, Menu menu) {
                return true;
            }

            @Override
            public boolean onCreateActionMode(ActionMode mode, Menu menu) {
                getMenuInflater().inflate(R.menu.folder_select_menu, menu);//Inflate the menu over action mode
                return true;
            }
            @Override
            public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
                return false;
            }

            @Override
            public void onDestroyActionMode(ActionMode mode) {

            }
        };`

![screenshot_1492695774](https://cloud.githubusercontent.com/assets/27816504/25233852/d9f04b9c-25fd-11e7-8c9c-41812cab1e6f.png)
![inkedscreenshot_1492695774_li](https://cloud.githubusercontent.com/assets/27816504/25233889/fc6c5ad0-25fd-11e7-8b2d-e9ae196cc5c4.jpg)

**Comment by garretyoder** [comment]
afollestad, app-theme-engine's developer took the repo down for the project when he discontinued it. Many apps still depend on it, so I kept my fork up as a mirror. However, I recommend using my own Colorful library as a better alternative that is not out of support. https://github.com/garretyoder/Colorful
